<a href="https://colab.research.google.com/github/ITLTVPo/Tensorflow/blob/master/Computer_vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
print(tf.__version__)

2.3.0


In [19]:
mnist = tf.keras.datasets.fashion_mnist

In [20]:
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

In [21]:
np.set_printoptions(linewidth=200)
print(training_images[0])
print(training_labels[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0  13  73   0   0   1   4   0   0   0   0   1   1   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3   0  36 136 127  62  54   0   0   0   1   3   4   0   0   3]
 [  0   0   0   0   0   0   0   0   0   0   0   0   6   0 102 204 176 134 144 123  23   0   0   0   0  12  10   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 155 236 207 178 107 156 161 109  64  23  77 130  72  15]
 [  0   0   0   0   0   0   0   0   0   0   0   1   0  69 207 223 218 216 216 163 127 121 122 146 141  88 172  66]
 [  0   0   0   0   0   0   0   0   0   1   1   1   0 200 232 232 233 229 223 22

In [22]:
training_images = training_images/255
test_images = test_images/255

In [23]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten(),
                                   tf.keras.layers.Dense(128, activation = tf.nn.relu),
                                   tf.keras.layers.Dense(10, activation = tf.nn.softmax)])

In [17]:
model = tf.keras.models.Sequential([tf.keras.layers.Flatten()])

In [30]:
model.compile(optimizer = tf.optimizers.Adam(),
              loss= 'sparse_categorical_crossentropy',
              metrics = ['accuracy'])
model.fit(training_images,training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2803 - accuracy: 0.8959
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2683 - accuracy: 0.8999
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2562 - accuracy: 0.9046
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2462 - accuracy: 0.9087
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2392 - accuracy: 0.9097


In [29]:
model.evaluate(test_images,test_labels)

313/313 [==============================] - 0s 1ms/step - loss: 0.3468 - accuracy: 0.8759


[0.346766859292984, 0.8758999705314636]

In [32]:
model.predict(test_images)[0]

array([5.3660024e-08, 6.3782286e-13, 2.3753949e-10, 1.5145929e-12, 4.0582893e-08, 9.6897036e-04, 7.4718542e-09, 2.6641656e-03, 1.4646902e-07, 9.9636662e-01], dtype=float32)